name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  job-a:
    name: Some long running job
    runs-on: ubuntu-22.04
    steps:
    - run: for ((i=1; i<=60; i++)); do echo "I am a log line produced at $(date)"; sleep 1; done

  job-b:
    name: Wait for the long running job
    runs-on: ubuntu-22.04
    steps:
    - name: Wait for check
      uses: fountainhead/action-wait-for-check@v1.1.0
      id: wait-for-check
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: Some long running job
        ref: ${{ github.sha }}

  job-c:
    name: Print the checks API output
    runs-on: ubuntu-22.04
    steps:
    - run: |
        check() {
          while true; do
            gh api /repos/:owner/:repo/commits/${{github.sha}}/check-runs | jq '.check_runs[] | select(.name == "Some long running job")'
            sleep 1
          done
        }
        export -f check
        trap 'kill -INT -$pid' INT
        timeout 2m bash -ce 'check' &
        pid=$!
        wait $pid
        

